sudo: false
language: ruby
cache: bundler
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.3.3
      env: STRICT_VARIABLES="yes" CHECK="beaker" BEAKER_set="debian9"
      bundler_args: --without rubocop
      services: docker
      sudo: required
  include:
  - rvm: 2.3.3
    env: STRICT_VARIABLES="yes" CHECK="beaker" BEAKER_set="debian9"
    bundler_args: --without rubocop
    services: docker
    sudo: required
  - rvm: 2.1.9
    env: STRICT_VARIABLES="yes" CHECK="rubocop"
    bundler_args: --without testing acceptance
  - rvm: 2.1.9
    env: STRICT_VARIABLES="yes" CHECK="lint"
    bundler_args: --without rubocop acceptance
  - rvm: 2.1.9
    env: STRICT_VARIABLES="yes" CHECK="validate"
    bundler_args: --without rubocop acceptance
  - rvm: 2.1.9
    env: STRICT_VARIABLES="yes" CHECK="spec"
    bundler_args: --without rubocop acceptance
  - rvm: 2.1.9
    env: STRICT_VARIABLES="yes" CHECK="beaker"
    bundler_args: --without rubocop
    services: docker
    sudo: required
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
<%     extra.keys.sort.each do |k| -%>
<%       next if k == 'rvm' -%>
    <%= k %>: <%= extra[k] %>
<%     end -%>
<%   end -%>
<% end -%>
notifications:
  email: false
<% if @configs['slack'] -%>
  slack:
    secure: <%= @configs['slack']['secure'] %>
<% end -%>
